import { IntentName, IntentSpec } from './types';

function spec(def: IntentSpec): IntentSpec {
  return def;
}

export const INTENT_REGISTRY: IntentSpec[] = [
  spec({
    name: 'summarize_day',
    domain: 'global',
    description: 'Summarize today activity',
    requiredSlots: [],
    optionalSlots: ['date', 'range'],
    examples: ['Summarize today', 'Give me my day summary'],
    confirmationRequired: false,
    handler: 'global',
    previewTitle: 'Daily summary',
    processingLabel: 'Relay is summarizing your day...',
    patterns: [/summari[sz]e.*today/i, /day summary/i, /summarize my day/i],
    keywords: ['summarize', 'today', 'day'],
  }),
  spec({
    name: 'summarize_week',
    domain: 'global',
    description: 'Summarize this week activity',
    requiredSlots: [],
    optionalSlots: ['range'],
    examples: ['Summarize this week', 'How did my week go'],
    confirmationRequired: false,
    handler: 'global',
    previewTitle: 'Weekly summary',
    processingLabel: 'Relay is summarizing your week...',
    patterns: [/summari[sz]e.*week/i, /week summary/i, /this week.*summary/i],
    keywords: ['summarize', 'week'],
  }),
  spec({
    name: 'summarize_custom_range',
    domain: 'global',
    description: 'Summarize a custom date range',
    requiredSlots: ['start_date', 'end_date'],
    optionalSlots: ['range'],
    examples: ['Summarize from Feb 1 to Feb 7'],
    confirmationRequired: false,
    handler: 'global',
    previewTitle: 'Custom summary',
    processingLabel: 'Relay is summarizing that date range...',
    patterns: [/summari[sz]e.*from .* to .*/i, /summary.*between .* and .*/i],
    keywords: ['summarize', 'from', 'to'],
  }),
  spec({
    name: 'what_do_i_have_today',
    domain: 'global',
    description: 'Ask what is scheduled today',
    requiredSlots: [],
    optionalSlots: ['date'],
    examples: ['What do I have today?', "What's on my schedule today?"],
    confirmationRequired: false,
    handler: 'global',
    previewTitle: 'Today timeline',
    processingLabel: 'Relay is checking your day...',
    patterns: [/what (do i have|is on).*(today|schedule)/i, /what.*today\??/i],
    keywords: ['what', 'today', 'schedule'],
  }),
  spec({
    name: 'what_should_i_do_today',
    domain: 'global',
    description: 'Ask Relay to generate a plan',
    requiredSlots: [],
    optionalSlots: ['range'],
    examples: ['What should I do today?', 'Make me a plan for today'],
    confirmationRequired: false,
    handler: 'global',
    previewTitle: 'Suggested plan',
    processingLabel: 'Relay is building your plan...',
    patterns: [/what should i do today/i, /make (me )?a plan/i, /plan my day/i],
    keywords: ['plan', 'today'],
  }),

  spec({
    name: 'create_task',
    domain: 'tasks',
    description: 'Create a new task',
    requiredSlots: ['title'],
    optionalSlots: ['date', 'time', 'person', 'category'],
    examples: ['Create a task to call the vet tomorrow', 'Remind me to buy milk'],
    confirmationRequired: true,
    handler: 'tasks',
    previewTitle: 'Create task',
    processingLabel: 'Relay is creating a task...',
    patterns: [
      /(?:create|add|new) (?:a )?task/i,
      /remind me to /i,
      /i need to /i,
      /todo[: ]/i,
    ],
    keywords: ['task', 'remind', 'todo', 'need to'],
  }),
  spec({
    name: 'delete_task',
    domain: 'tasks',
    description: 'Delete an existing task',
    requiredSlots: ['task_ref'],
    optionalSlots: [],
    examples: ['Delete task call the vet', 'Remove pick up Emily task'],
    confirmationRequired: true,
    handler: 'tasks',
    previewTitle: 'Delete task',
    processingLabel: 'Relay is preparing task deletion...',
    patterns: [/delete .*task/i, /remove .*task/i, /trash .*task/i],
    keywords: ['delete', 'remove', 'task'],
  }),
  spec({
    name: 'complete_task',
    domain: 'tasks',
    description: 'Complete an existing task',
    requiredSlots: ['task_ref'],
    optionalSlots: [],
    examples: ['Mark call the vet done', 'Complete grocery task'],
    confirmationRequired: true,
    handler: 'tasks',
    previewTitle: 'Complete task',
    processingLabel: 'Relay is marking that complete...',
    patterns: [/mark .* (done|complete)/i, /complete .*task/i, /finished .*task/i],
    keywords: ['done', 'complete', 'finish'],
  }),
  spec({
    name: 'reschedule_task',
    domain: 'tasks',
    description: 'Reschedule a task',
    requiredSlots: ['task_ref', 'date'],
    optionalSlots: ['time'],
    examples: ['Move call the vet to next Tuesday'],
    confirmationRequired: true,
    handler: 'tasks',
    previewTitle: 'Reschedule task',
    processingLabel: 'Relay is rescheduling that task...',
    patterns: [/reschedule .*task/i, /move .*task .* to /i, /push .*task/i],
    keywords: ['reschedule', 'move', 'task'],
  }),
  spec({
    name: 'list_tasks',
    domain: 'tasks',
    description: 'List open/completed tasks',
    requiredSlots: [],
    optionalSlots: ['category', 'date'],
    examples: ['Show my tasks', 'List overdue tasks'],
    confirmationRequired: false,
    handler: 'tasks',
    previewTitle: 'Task list',
    processingLabel: 'Relay is checking your tasks...',
    patterns: [/show .*tasks/i, /list .*tasks/i, /what tasks/i],
    keywords: ['show', 'list', 'tasks'],
  }),

  spec({
    name: 'create_event',
    domain: 'calendar',
    description: 'Create a calendar event',
    requiredSlots: ['title', 'date'],
    optionalSlots: ['time', 'location', 'person'],
    examples: ['Schedule a dentist appointment next Thursday at 3pm'],
    confirmationRequired: true,
    handler: 'calendar',
    previewTitle: 'Create event',
    processingLabel: 'Relay is scheduling that event...',
    patterns: [
      /schedule .* (appointment|meeting|event|visit)/i,
      /add .* to (my )?calendar/i,
      /create .*event/i,
    ],
    keywords: ['schedule', 'appointment', 'event', 'calendar'],
  }),
  spec({
    name: 'delete_event',
    domain: 'calendar',
    description: 'Delete an existing event',
    requiredSlots: ['event_ref'],
    optionalSlots: [],
    examples: ['Delete dentist appointment', 'Remove school pickup event'],
    confirmationRequired: true,
    handler: 'calendar',
    previewTitle: 'Delete event',
    processingLabel: 'Relay is preparing event deletion...',
    patterns: [/delete .* (appointment|event|meeting|visit)/i, /remove .* (appointment|event|meeting|visit)/i],
    keywords: ['delete', 'remove', 'event', 'appointment'],
  }),
  spec({
    name: 'move_event',
    domain: 'calendar',
    description: 'Move an existing event',
    requiredSlots: ['event_ref', 'date'],
    optionalSlots: ['time'],
    examples: ['Move dentist appointment to Friday at 10am'],
    confirmationRequired: true,
    handler: 'calendar',
    previewTitle: 'Move event',
    processingLabel: 'Relay is moving that event...',
    patterns: [/move .* (appointment|event|meeting)/i, /reschedule .* (appointment|event)/i],
    keywords: ['move', 'reschedule', 'event'],
  }),
  spec({
    name: 'what_is_next_event',
    domain: 'calendar',
    description: 'Ask what event comes next',
    requiredSlots: [],
    optionalSlots: ['date'],
    examples: ['What is my next event?', 'What do I have next?'],
    confirmationRequired: false,
    handler: 'calendar',
    previewTitle: 'Next event',
    processingLabel: 'Relay is checking your upcoming events...',
    patterns: [/what( is|'s) my next (event|appointment)/i, /next event/i],
    keywords: ['next', 'event'],
  }),

  spec({
    name: 'plan_meal',
    domain: 'meals',
    description: 'Plan a meal for a day/slot',
    requiredSlots: ['title'],
    optionalSlots: ['date', 'meal_type'],
    examples: ['Plan tacos for Tuesday dinner'],
    confirmationRequired: true,
    handler: 'meals',
    previewTitle: 'Plan meal',
    processingLabel: 'Relay is planning your meal...',
    patterns: [/plan .* (dinner|lunch|breakfast|meal)/i, /add .*meal/i],
    keywords: ['meal', 'dinner', 'lunch', 'breakfast'],
  }),
  spec({
    name: 'generate_week_plan',
    domain: 'meals',
    description: 'Generate a weekly meal plan',
    requiredSlots: [],
    optionalSlots: ['category'],
    examples: ['Generate a meal plan for next week'],
    confirmationRequired: true,
    handler: 'meals',
    previewTitle: 'Generate week meal plan',
    processingLabel: 'Relay is generating your week plan...',
    patterns: [/generate .*week.*meal/i, /plan meals for (this|next) week/i],
    keywords: ['generate', 'week', 'meal', 'plan'],
  }),
  spec({
    name: 'add_grocery_item',
    domain: 'meals',
    description: 'Add item to grocery list',
    requiredSlots: ['item'],
    optionalSlots: ['amount'],
    examples: ['Add milk to grocery list'],
    confirmationRequired: true,
    handler: 'meals',
    previewTitle: 'Add grocery item',
    processingLabel: 'Relay is updating your grocery list...',
    patterns: [/add .* to (the )?grocery list/i, /grocery list.* add/i],
    keywords: ['grocery', 'add'],
  }),
  spec({
    name: 'import_recipe_link',
    domain: 'meals',
    description: 'Import a recipe URL',
    requiredSlots: ['url'],
    optionalSlots: [],
    examples: ['Import this recipe link https://...'],
    confirmationRequired: true,
    handler: 'meals',
    previewTitle: 'Import recipe link',
    processingLabel: 'Relay is importing that recipe link...',
    patterns: [/import .*recipe.*https?:\/\//i, /recipe link/i, /paste .*recipe/i],
    keywords: ['import', 'recipe', 'link'],
  }),

  spec({
    name: 'add_bill',
    domain: 'finances',
    description: 'Add a bill',
    requiredSlots: ['title', 'amount', 'date'],
    optionalSlots: ['recurrence'],
    examples: ['Add internet bill 89 dollars due on the 12th monthly'],
    confirmationRequired: true,
    handler: 'finances',
    previewTitle: 'Add bill',
    processingLabel: 'Relay is adding that bill...',
    patterns: [/add .* bill/i, /new bill/i, /bill due/i],
    keywords: ['bill', 'due', 'payment'],
  }),
  spec({
    name: 'mark_bill_paid',
    domain: 'finances',
    description: 'Mark an existing bill as paid',
    requiredSlots: ['title'],
    optionalSlots: ['amount'],
    examples: ['Mark electricity bill paid', 'Bill paid for internet'],
    confirmationRequired: true,
    handler: 'finances',
    previewTitle: 'Mark bill paid',
    processingLabel: 'Relay is preparing bill payment update...',
    patterns: [/mark .*bill .*paid/i, /bill .* paid/i, /paid .*bill/i],
    keywords: ['bill', 'paid'],
  }),
  spec({
    name: 'add_subscription',
    domain: 'finances',
    description: 'Add a subscription',
    requiredSlots: ['title', 'amount'],
    optionalSlots: ['date', 'recurrence'],
    examples: ['Add a 16 dollar monthly music subscription'],
    confirmationRequired: true,
    handler: 'finances',
    previewTitle: 'Add subscription',
    processingLabel: 'Relay is adding that subscription...',
    patterns: [/add .*subscription/i, /new subscription/i, /subscribe/i],
    keywords: ['subscription', 'renew', 'monthly'],
  }),
  spec({
    name: 'cancel_subscription',
    domain: 'finances',
    description: 'Cancel an existing subscription',
    requiredSlots: ['title'],
    optionalSlots: [],
    examples: ['Cancel music family subscription', 'Stop Netflix subscription'],
    confirmationRequired: true,
    handler: 'finances',
    previewTitle: 'Cancel subscription',
    processingLabel: 'Relay is preparing subscription cancellation...',
    patterns: [/cancel .*subscription/i, /stop .*subscription/i, /remove .*subscription/i],
    keywords: ['cancel', 'stop', 'subscription'],
  }),
  spec({
    name: 'explain_spending',
    domain: 'finances',
    description: 'Explain spending trend',
    requiredSlots: [],
    optionalSlots: ['range', 'category'],
    examples: ['Explain my spending this week'],
    confirmationRequired: false,
    handler: 'finances',
    previewTitle: 'Spending explanation',
    processingLabel: 'Relay is analyzing your finances...',
    patterns: [/explain .*spending/i, /where is my money going/i, /spending summary/i],
    keywords: ['spending', 'money', 'finance'],
  }),

  spec({
    name: 'log_feeding',
    domain: 'pets',
    description: 'Log pet feeding',
    requiredSlots: ['pet'],
    optionalSlots: ['time', 'amount'],
    examples: ['Log feeding for Luna at 6pm'],
    confirmationRequired: true,
    handler: 'pets',
    previewTitle: 'Log feeding',
    processingLabel: 'Relay is logging that feeding...',
    patterns: [/log .*feeding/i, /feed .* (dog|cat|pet|[A-Za-z]+)/i],
    keywords: ['feed', 'feeding', 'pet'],
  }),
  spec({
    name: 'add_medication',
    domain: 'pets',
    description: 'Add pet medication schedule',
    requiredSlots: ['pet', 'title'],
    optionalSlots: ['recurrence', 'time'],
    examples: ['Add medication for Luna every morning'],
    confirmationRequired: true,
    handler: 'pets',
    previewTitle: 'Add medication',
    processingLabel: 'Relay is adding pet medication...',
    patterns: [/add .*medication/i, /pet meds/i, /medicine for/i],
    keywords: ['medication', 'medicine', 'pet'],
  }),
  spec({
    name: 'mark_medication_given',
    domain: 'pets',
    description: 'Mark pet medication as given',
    requiredSlots: ['pet', 'title'],
    optionalSlots: ['time'],
    examples: ['Mark Luna flea medication given', 'Gave Buddy medicine'],
    confirmationRequired: true,
    handler: 'pets',
    previewTitle: 'Mark medication given',
    processingLabel: 'Relay is preparing medication completion...',
    patterns: [/mark .*medication .*given/i, /gave .*medication/i, /gave .*medicine/i],
    keywords: ['medication', 'given', 'medicine'],
  }),
  spec({
    name: 'schedule_vet_visit',
    domain: 'pets',
    description: 'Schedule a vet visit',
    requiredSlots: ['pet', 'date'],
    optionalSlots: ['time', 'reason'],
    examples: ['Schedule a vet visit for Buddy next Tuesday at 3pm'],
    confirmationRequired: true,
    handler: 'pets',
    previewTitle: 'Schedule vet visit',
    processingLabel: 'Relay is scheduling that vet visit...',
    patterns: [/schedule .*vet/i, /vet appointment/i],
    keywords: ['vet', 'appointment', 'pet'],
  }),
  spec({
    name: 'complete_vet_visit',
    domain: 'pets',
    description: 'Mark a vet visit complete',
    requiredSlots: ['pet'],
    optionalSlots: ['date', 'reason'],
    examples: ['Mark Luna vet visit complete', 'Completed vet appointment for Buddy'],
    confirmationRequired: true,
    handler: 'pets',
    previewTitle: 'Complete vet visit',
    processingLabel: 'Relay is preparing vet visit completion...',
    patterns: [/mark .*vet .*complete/i, /completed .*vet/i, /vet visit .*done/i],
    keywords: ['vet', 'complete', 'appointment'],
  }),

  spec({
    name: 'create_note',
    domain: 'notes',
    description: 'Create a note',
    requiredSlots: ['title'],
    optionalSlots: ['query'],
    examples: ['Create a note about tax deductions'],
    confirmationRequired: true,
    handler: 'notes',
    previewTitle: 'Create note',
    processingLabel: 'Relay is creating your note...',
    patterns: [/create .*note/i, /save this note/i, /remember this/i],
    keywords: ['note', 'remember', 'save'],
  }),
  spec({
    name: 'delete_note',
    domain: 'notes',
    description: 'Delete a note',
    requiredSlots: ['query'],
    optionalSlots: [],
    examples: ['Delete note about taxes', 'Remove the dentist follow-up note'],
    confirmationRequired: true,
    handler: 'notes',
    previewTitle: 'Delete note',
    processingLabel: 'Relay is preparing note deletion...',
    patterns: [/delete .*note/i, /remove .*note/i, /trash .*note/i],
    keywords: ['delete', 'remove', 'note'],
  }),
  spec({
    name: 'save_summary_as_note',
    domain: 'notes',
    description: 'Save summary as note',
    requiredSlots: [],
    optionalSlots: ['range'],
    examples: ['Save this summary as a note'],
    confirmationRequired: true,
    handler: 'notes',
    previewTitle: 'Save summary',
    processingLabel: 'Relay is saving that summary...',
    patterns: [/save .*summary.*note/i, /turn .*summary.*note/i],
    keywords: ['save', 'summary', 'note'],
  }),
  spec({
    name: 'find_note',
    domain: 'notes',
    description: 'Search notes/documents',
    requiredSlots: ['query'],
    optionalSlots: ['category'],
    examples: ['Find my tax note', 'Search notes for passport'],
    confirmationRequired: false,
    handler: 'notes',
    previewTitle: 'Find note',
    processingLabel: 'Relay is searching your notes...',
    patterns: [/find .*note/i, /search .*notes?/i, /where is my .*note/i],
    keywords: ['find', 'search', 'note'],
  }),

  spec({
    name: 'assign_chore',
    domain: 'family',
    description: 'Assign a chore to family member',
    requiredSlots: ['member', 'title'],
    optionalSlots: ['date'],
    examples: ['Assign dishes to Alex tonight'],
    confirmationRequired: true,
    handler: 'family',
    previewTitle: 'Assign chore',
    processingLabel: 'Relay is assigning that chore...',
    patterns: [/assign .* to /i, /give .* chore/i],
    keywords: ['assign', 'chore', 'family'],
  }),
  spec({
    name: 'reassign_chore',
    domain: 'family',
    description: 'Reassign an existing family chore',
    requiredSlots: ['task_ref', 'member'],
    optionalSlots: ['date'],
    examples: ['Reassign dishes to Michael', 'Move school pickup task to Jaiden'],
    confirmationRequired: true,
    handler: 'family',
    previewTitle: 'Reassign chore',
    processingLabel: 'Relay is preparing reassignment...',
    patterns: [/reassign .* to /i, /move .*task .* to /i, /assign .*task .* to /i],
    keywords: ['reassign', 'move', 'task', 'assign'],
  }),
  spec({
    name: 'add_family_event',
    domain: 'family',
    description: 'Add family event',
    requiredSlots: ['title', 'date'],
    optionalSlots: ['time', 'member'],
    examples: ['Add family event recital Friday at 6pm'],
    confirmationRequired: true,
    handler: 'family',
    previewTitle: 'Add family event',
    processingLabel: 'Relay is adding that family event...',
    patterns: [/add .*family event/i, /family calendar/i, /schedule .*for the family/i],
    keywords: ['family', 'event', 'calendar'],
  }),
  spec({
    name: 'who_is_responsible',
    domain: 'family',
    description: 'Find who is responsible for a task',
    requiredSlots: ['task_ref'],
    optionalSlots: [],
    examples: ['Who is responsible for pickup?'],
    confirmationRequired: false,
    handler: 'family',
    previewTitle: 'Responsibility lookup',
    processingLabel: 'Relay is checking assignments...',
    patterns: [/who is responsible/i, /who has .*task/i],
    keywords: ['who', 'responsible', 'assigned'],
  }),

  spec({
    name: 'small_talk_qna',
    domain: 'system',
    description: 'Small talk or acknowledgement',
    requiredSlots: [],
    optionalSlots: [],
    examples: ['Thanks', 'How are you?'],
    confirmationRequired: false,
    handler: 'system',
    previewTitle: 'Conversation',
    processingLabel: 'Relay is responding...',
    patterns: [/(^|\b)(thanks|thank you|hello|hi|hey|how are you)(\b|$)/i],
    keywords: ['thanks', 'hello', 'hi', 'hey'],
  }),
  spec({
    name: 'unknown_intent',
    domain: 'system',
    description: 'Fallback intent when parsing fails',
    requiredSlots: [],
    optionalSlots: [],
    examples: ['Do something'],
    confirmationRequired: false,
    handler: 'system',
    previewTitle: 'Need clarification',
    processingLabel: 'Relay is clarifying...',
    patterns: [],
    keywords: [],
  }),
];

export const INTENT_BY_NAME = INTENT_REGISTRY.reduce<Record<IntentName, IntentSpec>>((acc, entry) => {
  acc[entry.name] = entry;
  return acc;
}, {} as Record<IntentName, IntentSpec>);
