import { useRouter } from 'expo-router';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { BubbleChip } from '@/components/relay/BubbleChip';
import { EmptyState } from '@/components/relay/EmptyState';
import { GlassCard } from '@/components/relay/GlassCard';
import { ds } from '@/constants/design-system';
import { NotesShell } from '../components/NotesShell';
import { useNotesStore } from '../notes-context';

export default function UploadDocConfirmScreen() {
  const router = useRouter() as any;
  const { state, addDocument, clearDocDraft } = useNotesStore();

  const draft = state.docDraft;
  if (!draft) {
    return (
      <NotesShell title="Confirm Upload" subtitle="No draft" onBack={() => router.replace('/notes')}>
        <EmptyState title="No upload draft" body="Start from Upload Document." />
      </NotesShell>
    );
  }

  const tags = state.tags.filter((tag) => draft.tagIds.includes(tag.id)).map((tag) => tag.label).join(', ') || 'No tags';

  return (
    <NotesShell title="Confirm Upload" subtitle="Relay understood this" onBack={() => router.back()}>
      <GlassCard blur>
        <Text style={styles.label}>Name</Text>
        <Text style={styles.value}>{draft.name}</Text>

        <Text style={styles.label}>Type</Text>
        <Text style={styles.value}>{draft.type.toUpperCase()}</Text>

        <Text style={styles.label}>Category</Text>
        <Text style={styles.value}>{draft.categorySlug}</Text>

        <Text style={styles.label}>Tags</Text>
        <Text style={styles.value}>{tags}</Text>

        <Text style={styles.label}>File</Text>
        <Text style={styles.value}>{draft.fileLabel}</Text>
      </GlassCard>

      <View style={styles.actions}>
        <BubbleChip
          icon="checkmark"
          label="Confirm"
          tone="success"
          onPress={() => {
            const id = addDocument({
              name: draft.name,
              type: draft.type,
              categorySlug: draft.categorySlug,
              tagIds: draft.tagIds,
              pinned: false,
              archived: false,
              source: 'upload',
              shared: false,
              addedBy: 'Jaiden',
              aiSummary: `Imported ${draft.type} document saved to ${draft.categorySlug}.`,
              extractedText: 'Mock extraction preview generated by Relay.',
            });
            clearDocDraft();
            router.replace(`/notes/doc/${id}`);
          }}
        />
        <BubbleChip icon="create-outline" label="Edit" tone="primary" onPress={() => router.back()} />
        <BubbleChip
          icon="close"
          label="Cancel"
          tone="neutral"
          onPress={() => {
            clearDocDraft();
            router.replace('/notes');
          }}
        />
      </View>
    </NotesShell>
  );
}

const styles = StyleSheet.create({
  label: {
    marginTop: ds.spacing.s8,
    fontFamily: ds.font,
    fontSize: 12,
    lineHeight: 16,
    color: ds.colors.textMuted,
    fontWeight: '700',
  },
  value: {
    marginTop: 2,
    fontFamily: ds.font,
    fontSize: 15,
    lineHeight: 20,
    color: ds.colors.text,
    fontWeight: '600',
  },
  actions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: ds.spacing.s8,
  },
});
